apiVersion: apps/v1
kind: Deployment
metadata:
  name: presidio-analyzer
  labels:
    app: presidio-analyzer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: presidio-analyzer
  template:
    metadata:
      labels:
        app: presidio-analyzer
    spec:
      containers:
      - name: presidio-analyzer
        image: mcr.microsoft.com/presidio-analyzer:latest
        ports:
        - containerPort: 3000
        env:
        - name: PRESIDIO_LOGGER_LEVEL
          value: "INFO"
---
apiVersion: v1
kind: Service
metadata:
  name: presidio-analyzer-service
  labels:
    app: presidio-analyzer
spec:
  selector:
    app: presidio-analyzer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer

